spring.application.name=apis
spring.datasource.url=jdbc:postgresql://localhost:5432/api_db
spring.datasource.username=postgres
spring.datasource.password=1989

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=my-secret-key-test